### ISSUE TITLE
A step missing in the setup documentation

### ISSUE THREAD

**Issue by spetrosi** [ralexander-phi/marp-to-pages#12]
After creating a repo from your template repo I need to make an additional step:
Go to Settings > Actions > General > in Workflow permissions select Read and Write permissions.
This is required by https://github.com/JamesIves/github-pages-deploy-action and because you use this action it is worth mentioning.

One nitpick is to have the setup procedure in steps not in subtitles for readability.

Thank you

**Comment by ralexander-phi** [comment]
Thanks for raising this issue! I missed this step.

Looking into it some more, I see that I can add permissions directly to the job in the workflow (more details linked in the PR). This way the workflow won't need an extra setup step.
