### ISSUE TITLE
Do not copy images if no images exist

### ISSUE THREAD

**Issue by spetrosi** [ralexander-phi/marp-to-pages#13]
If I remove the images directory the workflow fails because it cannot find the images to copy. 
I think the same applies to the docs directory.
The workflow must work on img and docs directories only if they exist and have some content.

**Comment by ralexander-phi** [comment]
Great point! I've updated the workflow to check if these folders exist, and then skip the associated tasks.

The workflow is messier than I'd like, but everyone is free to delete these steps in their repo if they don't plan on using the folders.

Thanks for reaching out!
